import { ossUrlMap } from "./oss-url-map";

/**
 * Resolve an asset path to a short-lived signed OSS URL (during event) or fall
 * back to the local /public/ path (before/after event).
 *
 * The URL map in lib/oss-url-map.ts is generated by
 * events/.../scripts/generate-oss-urls.py with a 5-day expiry on each URL.
 * After the event run the script with --clear to empty the map; the helper
 * will then fall back to local /public/ files served from git LFS.
 */
export function assetUrl(path: string | null | undefined): string {
  if (!path) return "";
  if (/^https?:\/\//i.test(path)) return path;
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return ossUrlMap[normalized] ?? normalized;
}
