import { ossUrlMap } from "../lib/ossUrlMap";

/**
 * Resolve an asset path to a short-lived signed OSS URL (during event) or fall
 * back to the local /public/ path (before/after event).
 *
 * The URL map in lib/ossUrlMap.ts is generated by scripts/generate-oss-urls.py
 * with a 5-day expiry on each URL. OSS objects are also deleted 5 days after
 * upload by the bucket lifecycle rule. After the event:
 *   python3 scripts/generate-oss-urls.py --clear
 * empties the map -> helper falls back to local /public/ files served from
 * git LFS (the canonical source of the original data).
 *
 * Absolute http(s) URLs pass through. Empty/nullish input returns "".
 */
export const useAssetUrl = (path: string | null | undefined): string => {
  if (!path) return "";
  if (/^https?:\/\//i.test(path)) return path;
  const normalized = path.startsWith("/") ? path : `/${path}`;
  return ossUrlMap[normalized] ?? normalized;
};
