// AUTO-GENERATED by scripts/generate-oss-urls.py. DO NOT EDIT BY HAND.
// Signed at: 2026-04-24T09:51:00+00:00
// Expires around: 2026-04-29T09:51:00+00:00 (5 days)
// Re-run the script before expiry if the event is still active.
export const ossUrlMap: Readonly<Record<string, string>> = {
  "/hedy.jpg": "https://web-dj-20260205.oss-ap-northeast-1.aliyuncs.com/yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/posters/short/hedy.jpg?OSSAccessKeyId=LTAI5tHGQx8to43h3a8g1Ywu&Expires=1777456260&Signature=cDOElEY0kS8hVeSXtY2GGcK0OzU%3D",
  "/map-1-journey.jpg": "https://web-dj-20260205.oss-ap-northeast-1.aliyuncs.com/yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/posters/short/map-1-journey.jpg?OSSAccessKeyId=LTAI5tHGQx8to43h3a8g1Ywu&Expires=1777456260&Signature=HN01UOcxr4fosKm1SROwkT%2Fpk50%3D",
  "/map-2-local.jpg": "https://web-dj-20260205.oss-ap-northeast-1.aliyuncs.com/yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/posters/short/map-2-local.jpg?OSSAccessKeyId=LTAI5tHGQx8to43h3a8g1Ywu&Expires=1777456260&Signature=07psrvman69IvTWChjJmsU2DADA%3D",
  "/qr-code.jpg": "https://web-dj-20260205.oss-ap-northeast-1.aliyuncs.com/yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/posters/short/qr-code.jpg?OSSAccessKeyId=LTAI5tHGQx8to43h3a8g1Ywu&Expires=1777456260&Signature=dzoNuVREt0axPMs4sQsuT3F7pyc%3D",
  "/shirley.jpg": "https://web-dj-20260205.oss-ap-northeast-1.aliyuncs.com/yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/posters/short/shirley.jpg?OSSAccessKeyId=LTAI5tHGQx8to43h3a8g1Ywu&Expires=1777456260&Signature=oVc9mTKs5RdY5PDRAvSA1ZrRwIY%3D",
  "/yale-bg1.jpg": "https://web-dj-20260205.oss-ap-northeast-1.aliyuncs.com/yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/posters/short/yale-bg1.jpg?OSSAccessKeyId=LTAI5tHGQx8to43h3a8g1Ywu&Expires=1777456260&Signature=5u3bCyL%2BVrue3fAQAVstLvOfJqQ%3D",
  "/yale_club_sh.jpg": "https://web-dj-20260205.oss-ap-northeast-1.aliyuncs.com/yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/posters/short/yale_club_sh.jpg?OSSAccessKeyId=LTAI5tHGQx8to43h3a8g1Ywu&Expires=1777456260&Signature=AwgheslnLwRvaWKfk79LIu%2FlCI8%3D",
  "/yue.jpg": "https://web-dj-20260205.oss-ap-northeast-1.aliyuncs.com/yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/posters/short/yue.jpg?OSSAccessKeyId=LTAI5tHGQx8to43h3a8g1Ywu&Expires=1777456260&Signature=35%2B9DjYSnwAnW%2FhLPH%2BRzWORAEc%3D",
  "/zhuwei.jpg": "https://web-dj-20260205.oss-ap-northeast-1.aliyuncs.com/yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/posters/short/zhuwei.jpg?OSSAccessKeyId=LTAI5tHGQx8to43h3a8g1Ywu&Expires=1777456260&Signature=CmGqILI1EbHZpWG5KbS5c8tW%2Fc8%3D",
  "/zichao.jpg": "https://web-dj-20260205.oss-ap-northeast-1.aliyuncs.com/yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/posters/short/zichao.jpg?OSSAccessKeyId=LTAI5tHGQx8to43h3a8g1Ywu&Expires=1777456260&Signature=ws3AGKPL8E0B7MS%2FaH%2FtUaBHrFA%3D",
  "/ziyue.jpg": "https://web-dj-20260205.oss-ap-northeast-1.aliyuncs.com/yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/posters/short/ziyue.jpg?OSSAccessKeyId=LTAI5tHGQx8to43h3a8g1Ywu&Expires=1777456260&Signature=wdl20FXtVsGrBDizr%2BASnvZBJFI%3D"
};
