#!/usr/bin/env python3
"""Sign OSS URLs for all event assets and write per-app TS maps.

Purpose:
  The 58 event JPEGs live in Alibaba OSS (bucket web-dj-20260205) under prefix
  yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event/. They are
  PRIVATE-ACL so they can only be fetched through time-limited signed URLs.
  This script signs every object with a 5-day expiry and writes the resulting
  {relative_path -> signed_url} map as a TypeScript constant for each of the
  three apps (Nuxt two-maps, Next.js posters/long, Next.js posters/short).

Usage:
  python3 scripts/generate-oss-urls.py
  # then commit the 3 regenerated .ts maps

Re-run whenever the signed URLs are about to expire and the event is still
running. Credentials are read from ~/.ossutilconfig.
"""
from __future__ import annotations

import datetime as _dt
import json
import sys
from pathlib import Path

try:
    import oss2
except ImportError:
    sys.exit("oss2 not installed. pip install oss2")

REPO_ROOT = Path(__file__).resolve().parents[3]
EVENT_ROOT = Path(__file__).resolve().parents[1]

BUCKET_NAME = "web-dj-20260205"
ENDPOINT = "https://oss-ap-northeast-1.aliyuncs.com"
PREFIX = "yalie/yale-club-of-shanghai/events/2026-04-alumni-welcome-event"
EXPIRES_SECONDS = 5 * 24 * 60 * 60

APPS = [
    {
        "sub_prefix": "two-maps",
        "target": EVENT_ROOT / "two-maps/web/lib/ossUrlMap.ts",
        "symbol": "ossUrlMap",
    },
    {
        "sub_prefix": "posters/long",
        "target": EVENT_ROOT / "posts/posters/long/lib/oss-url-map.ts",
        "symbol": "ossUrlMap",
    },
    {
        "sub_prefix": "posters/short",
        "target": EVENT_ROOT / "posts/posters/short/lib/oss-url-map.ts",
        "symbol": "ossUrlMap",
    },
]


def load_credentials() -> tuple[str, str]:
    cfg = Path("~/.ossutilconfig").expanduser()
    if not cfg.exists():
        sys.exit("~/.ossutilconfig not found. Run `ossutil config` first.")
    values: dict[str, str] = {}
    for raw in cfg.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("["):
            continue
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    ak = values.get("accessKeyID") or values.get("accesskeyid")
    sk = values.get("accessKeySecret") or values.get("accesskeysecret")
    if not ak or not sk:
        sys.exit("ossutilconfig missing accessKeyID / accessKeySecret")
    return ak, sk


def build_maps(bucket: "oss2.Bucket") -> dict[str, dict[str, str]]:
    maps: dict[str, dict[str, str]] = {app["sub_prefix"]: {} for app in APPS}
    for obj in oss2.ObjectIterator(bucket, prefix=PREFIX + "/"):
        if not obj.key.endswith(".jpg"):
            continue
        rel = obj.key[len(PREFIX) + 1 :]
        matched = False
        for app in APPS:
            sub = app["sub_prefix"]
            if rel.startswith(sub + "/"):
                inner = "/" + rel[len(sub) + 1 :]
                url = bucket.sign_url("GET", obj.key, EXPIRES_SECONDS, slash_safe=True)
                if url.startswith("http://"):
                    url = "https://" + url[len("http://") :]
                maps[sub][inner] = url
                matched = True
                break
        if not matched:
            print(f"warn: unmatched key skipped: {obj.key}", file=sys.stderr)
    return maps


def render_ts(symbol: str, entries: dict[str, str]) -> str:
    generated_at = _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds")
    expiry_date = (
        _dt.datetime.now(_dt.timezone.utc)
        + _dt.timedelta(seconds=EXPIRES_SECONDS)
    ).isoformat(timespec="seconds")
    body = ",\n".join(
        f'  {json.dumps(k)}: {json.dumps(v)}' for k, v in sorted(entries.items())
    )
    return (
        "// AUTO-GENERATED by scripts/generate-oss-urls.py. DO NOT EDIT BY HAND.\n"
        f"// Signed at: {generated_at}\n"
        f"// Expires around: {expiry_date} (5 days)\n"
        "// Re-run the script before expiry if the event is still active.\n"
        f"export const {symbol}: Readonly<Record<string, string>> = {{\n"
        f"{body}\n"
        "};\n"
    )


def main() -> None:
    clear = "--clear" in sys.argv[1:]
    if clear:
        for app in APPS:
            target = Path(app["target"])
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(render_ts(app["symbol"], {}))
            print(f"cleared -> {target.relative_to(REPO_ROOT)}")
        print("All maps emptied. Apps will fall back to local /public/ serving.")
        return
    ak, sk = load_credentials()
    auth = oss2.Auth(ak, sk)
    bucket = oss2.Bucket(auth, ENDPOINT, BUCKET_NAME)
    maps = build_maps(bucket)
    total = 0
    for app in APPS:
        entries = maps[app["sub_prefix"]]
        total += len(entries)
        ts = render_ts(app["symbol"], entries)
        target = Path(app["target"])
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(ts)
        print(f"wrote {len(entries):3d} urls -> {target.relative_to(REPO_ROOT)}")
    print(f"total signed: {total}")


if __name__ == "__main__":
    main()
